# DB-GPT Shell Agent Docker Compose Configuration
services:
  shell-agent:
    build:
      context: ../..
      dockerfile: docker/cc-ollama/Dockerfile.shell-agent
    container_name: dbgpt-shell-agent
    volumes:
      # Persist Ollama models
      - shell-agent-ollama:/root/.ollama
      # Mount the project directory for code auditing and shell operations
      - ../..:/app/project
    ports:
      # Expose Ollama API port
      - "11434:11434"
    environment:
      - OLLAMA_HOST=localhost
      - OLLAMA_MODELS=/root/.ollama/models
    # Enable interactive terminal
    stdin_open: true
    tty: true
    # Ensure container keeps running
    restart: unless-stopped
    # Add capability to manage system resources
    cap_add:
      - SYS_RESOURCE
    # Allocate at least 8GB memory for large models
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    # Use host network for better performance
    network_mode: "bridge"

volumes:
  shell-agent-ollama:
    driver: local
